"""Add EC2 challenges tables

Revision ID: 001_ec2_challenges
Revises: 
Create Date: 2024-01-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "001_ec2_challenges"
down_revision = None
branch_labels = None
depends_on = None


def upgrade(op=None):
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create EC2Config table
    op.create_table(
        'ec2_config',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('aws_access_key_id', sa.String(length=20), nullable=True),
        sa.Column('aws_secret_access_key', sa.String(length=40), nullable=True),
        sa.Column('region', sa.String(length=32), nullable=True),
        sa.Column('default_instance_type', sa.String(length=32), nullable=True),
        sa.Column('default_security_group', sa.String(length=128), nullable=True),
        sa.Column('default_key_name', sa.String(length=128), nullable=True),
        sa.Column('default_subnet_id', sa.String(length=128), nullable=True),
        sa.Column('max_instance_time', sa.Integer(), nullable=True),
        sa.Column('auto_stop_enabled', sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Create EC2ChallengeTracker table
    op.create_table(
        'ec2_challenge_tracker',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('owner_id', sa.String(length=64), nullable=True),
        sa.Column('challenge_id', sa.Integer(), nullable=True),
        sa.Column('instance_id', sa.String(length=128), nullable=True),
        sa.Column('timestamp', sa.Integer(), nullable=True),
        sa.Column('revert_time', sa.Integer(), nullable=True),
        sa.Column('host', sa.String(length=128), nullable=True),
        sa.Column('flag', sa.String(length=128), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ec2_challenge_tracker_challenge_id', 'ec2_challenge_tracker', ['challenge_id'])
    op.create_index('ix_ec2_challenge_tracker_instance_id', 'ec2_challenge_tracker', ['instance_id'])
    op.create_index('ix_ec2_challenge_tracker_owner_id', 'ec2_challenge_tracker', ['owner_id'])
    op.create_index('ix_ec2_challenge_tracker_revert_time', 'ec2_challenge_tracker', ['revert_time'])
    op.create_index('ix_ec2_challenge_tracker_timestamp', 'ec2_challenge_tracker', ['timestamp'])
    
    # Create EC2Challenge table
    op.create_table(
        'ec2_challenge',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('ami_id', sa.String(length=128), nullable=True),
        sa.Column('instance_type', sa.String(length=32), nullable=True),
        sa.Column('security_group', sa.String(length=128), nullable=True),
        sa.Column('key_name', sa.String(length=128), nullable=True),
        sa.Column('subnet_id', sa.String(length=128), nullable=True),
        sa.Column('setup_script', sa.Text(), nullable=True),
        sa.Column('guide', sa.Text(), nullable=True),
        sa.Column('auto_stop_time', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['id'], ['challenges.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ec2_challenge_ami_id', 'ec2_challenge', ['ami_id'])
    
    # Create EC2History table
    op.create_table(
        'ec2_history',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('instance_id', sa.String(length=128), nullable=True),
        sa.Column('challenge_id', sa.Integer(), nullable=True),
        sa.Column('start_time', sa.Integer(), nullable=True),
        sa.Column('end_time', sa.Integer(), nullable=True),
        sa.Column('solved', sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ec2_history_id', 'ec2_history', ['id'])
    
    # ### end Alembic commands ###


def downgrade(op=None):
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ec2_history_id', table_name='ec2_history')
    op.drop_table('ec2_history')
    op.drop_index('ix_ec2_challenge_ami_id', table_name='ec2_challenge')
    op.drop_table('ec2_challenge')
    op.drop_index('ix_ec2_challenge_tracker_timestamp', table_name='ec2_challenge_tracker')
    op.drop_index('ix_ec2_challenge_tracker_revert_time', table_name='ec2_challenge_tracker')
    op.drop_index('ix_ec2_challenge_tracker_owner_id', table_name='ec2_challenge_tracker')
    op.drop_index('ix_ec2_challenge_tracker_instance_id', table_name='ec2_challenge_tracker')
    op.drop_index('ix_ec2_challenge_tracker_challenge_id', table_name='ec2_challenge_tracker')
    op.drop_table('ec2_challenge_tracker')
    op.drop_table('ec2_config')
    # ### end Alembic commands ###
